---
title: "$2^3$ Factorial Design"
author: "Dr Austin R Brown"
institute: "Kennesaw State University"
format:
  beamer:
    include-in-header:
      - text: |
          \usepackage{tabularx}
          \usepackage{booktabs}
editor: visual
execute:
  echo: true
  include: true
  warning: false
  message: false
  tidy: false
---

## Introduction

-   In the last section, we were introduced to the concept of a $2^2$ factorial design.

\vskip 0.15 in

-   In this section, we will extend this concept to a $2^3$ factorial design, in which we have three treatment factors, each with two levels.

\vskip 0.15 in

-   As before, we'll begin with a scenario and work through the analysis steps, almost all of which we've familiarized ourselves with in other lectures.

## Experimental Example

-   A chess app company called **Pawn Shop** is interested in understanding how different app features influences monthly user purchases (in dollars).

\vskip 0.15 in

-   The app development team has identified three key factors that could impact spending behavior: **A**: Subscription Type (Basic - vs Premium +) **B**: In-App Purchase Offers (No - vs Yes +) **C**: Personalized Coaching Feature (Off - vs On +)

\vskip 0.15 in

-   For each of the $2^3=8$ treatment combinations, suppose we randomly recruit $r=2$ customers to pilot the app. After a month of using the app, we record their monthly purchases.
    -   The data are stored in the `2^3 Chess Example.xlsx`

## Considering the Data Structure

-   The data structure for a $2^3$ factorial design is similar to that of a $2^2$ factorial design, but with an additional factor.

\begin{table}[h]
    \centering
    \begin{tabular}{cc l cccc}
        \toprule
        A & B & \text{Treatment Combo} & \text{Rep 1} & \text{Rep 2} & \text{Rep 3} & \text{Total} \\
        \midrule
        - & - & Enabled/Enhanced  & 151.80  & 179.99 & 154.92 & 486.71 \\
        - & + & Enabled/Points    & 136.15 & 141.49 & 152.41 & 430.05 \\
        + & - & Disabled/Enhanced & 129.30  & 119.98 & 131.79 & 381.07 \\
        + & + & Disabled/Points   & 107.22 &  44.72 &  77.85 & 229.79 \\
        \bottomrule
    \end{tabular}
    \caption{\(2^2\) Factorial Design with Treatment Combinations and Replicates}
\end{table}
