---
title: "An Introduction to Python Programming for Data Science"
format: beamer
editor: visual
author: "Dr. Austin Brown"
institute: "Kennesaw State University"
execute: 
  echo: true
  include: true
  warning: false
  message: false
  tidy: false
---

## Why Learn Python?

-   You may be asking yourself, out of all of the possible programming languages which exist, why should I spend time learning Python?

\vskip 0.10 in

-   Great question!

\vskip 0.10 in

-   Python is a useful tool and worthwhile to learn for several reasons:
    1.  It's free!
    2.  Because it's open source, thousands of people have contributed packages and functions at a pace that proprietary softwares can't compete with
    3.  It is a very flexible and robust general programming language, meaning there's a lot you can do with it in the data science space and beyond!
    4.  It has become basically the standard in industry

## So What is Python?

-   Python is command-line, object-oriented general programming language commonly used for data analysis, data science and statistics.

\vskip 0.10 in

-   \textbf{Command-line} means that we have to give it commands in order for us to get it to do something. For example:

```{python}
#| echo: true
#| include: true
## The sum of 2 & 2 ##
2 + 2
```